name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  default:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - macos-26-intel
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          path: local-action

      - name: Create fake audit.json
        run: echo '{"advisories":[],"abandoned":[]}' > audit.json

      - name: Create fake composer.lock
        run: echo '{"packages":[{"name":"psr/log"}],"packages-dev":[]}' > composer.lock

      - uses: ./local-action
        id: subject

      - name: Assert output contains SARIF
        if: steps.subject.outputs.sarif == ''
        run: exit 1

  customization:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - macos-26-intel
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          path: local-action

      - name: Create fake root directory
        run: mkdir -p foo/bar

      - name: Create fake audit.json
        run: echo '{"advisories":[],"abandoned":[]}' > foo/bar/audit-baz.json

      - name: Create fake composer.lock
        run: echo '{"packages":[{"name":"psr/log"}],"packages-dev":[]}' > foo/bar/composer-baz.lock

      - uses: ./local-action
        id: subject
        with:
          audit: foo/bar/audit-baz.json
          lock: foo/bar/composer-baz.lock
          root: foo

      - name: Assert output contains SARIF
        if: steps.subject.outputs.sarif == ''
        run: exit 1

  wait-for-all-test:
    if: cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure')
    needs:
      - default
      - customization
    runs-on: ubuntu-latest
    steps:
      - name: Assert no required jobs were cancelled or failed
        run: exit 1
